### ISSUE TITLE
Base64 only works on charset UTF-16LE

### ISSUE THREAD

**Issue by kokoropie** [dathoangnd/truedevtools.com#4]
**This must be done to see the problem**
1. Go to truedevtools.com
2. Select Base64 Encoder / Decoder
3. Select "Decode"
4. Try some encoded `eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9` (which used UTF-8 for `{"alg":"HS256","typ":"JWT"}`)
5. Get error

**Comment by dathoangnd** [comment]
@kokoropie Fixed it now. Since I do not want to add another dropdown just to select the encoding, I have come up with a heuristic algorithm to detect the source encoding, and it works well for most cases.

![Screenshot 2024-05-04 at 12 33 15](https://github.com/dathoangnd/truedevtools.com/assets/26485062/cd469107-fa30-4196-bf68-bc7b87f63e12)

**Comment by kokoropie** [comment]
works well now
